import { draftGrades, hindsightRedraft, pickReports } from "../../shared/draft";
import { cancelReversals, playerJourney, Seasons, tradeLedger, tradeVerdicts, waiverBattles, waiverRecord } from "../../shared/moves";
import { fixtureLuck } from "../../shared/results";
import { managerLabels } from "../../shared/standings";
import { draftDay } from "../../shared/waivers";
const B = "https://drafty-in-here.amooneywalsh.workers.dev/api/";
const g = async (p: string) => (await (await fetch(B + p)).json()).data;
const league = await g("league"), players = await g("players"), trades = await g("trades"), tx = await g("transactions"), draft = await g("draft"), game = await g("game");
const gws = []; for (let i = 1; i <= game.current_event; i++) gws.push(await g(`gw/${i}`));
const seasons = new Seasons(gws); const L = managerLabels(league.league_entries); const ids = [...L.keys()];
const P = new Map(players.players.map((p: any) => [p.id, p.name]));
const t = cancelReversals(trades.trades).trades;
const v = tradeVerdicts(t, seasons, tx.transactions); const led = tradeLedger(v, ids).sort((a,b)=>b.net-a.net);
console.log("ledger", led.map(r=>[L.get(r.entryId), r.trades, r.won, r.lost, r.net]));
const big = v.filter(x=>!x.pending).sort((a,b)=>b.margin-a.margin)[0];
console.log("bigtrade", big.event, L.get(big.winner!), big.margin, L.get(big.offerer.entryId), big.offerer.received.map(r=>P.get(r.element)), L.get(big.receiver.entryId), big.receiver.received.map(r=>P.get(r.element)));
console.log("trades total", v.length);
const luck = fixtureLuck(league).sort((a,b)=>b.luck-a.luck); console.log("luck", luck.map(r=>[L.get(r.entryId), r.luck]));
const reps = pickReports(draft.choices, seasons); const gr = draftGrades(reps); console.log("grades", gr.slice(0,3).map(x=>[L.get(x.entryId), x.points, x.value]), gr.slice(-1).map(x=>[L.get(x.entryId)]));
const steals = [...reps].sort((a:any,b:any)=>b.value-a.value).slice(0,3); console.log("steals", steals.map((s:any)=>[P.get(s.element), s.index, L.get(s.entryId), s.points, s.value]));
const busts = [...reps].sort((a:any,b:any)=>a.value-b.value).slice(0,2); console.log("busts", busts.map((s:any)=>[P.get(s.element), s.index, L.get(s.entryId), s.points]));
const rd = hindsightRedraft(draft.choices, seasons, players.players, players.rules).slice(0,3); console.log("redraft", rd.map((r:any)=>[r.index, L.get(r.entryId), P.get(r.actual), P.get(r.hindsight)]));
const dd = draftDay(draft.choices, ids); console.log("autos", dd.filter(r=>r.autoPicks.length).map(r=>[L.get(r.entryId), r.autoPicks.length]));
const wb = waiverBattles(tx.transactions, seasons); console.log("battles", wb.length, [...wb].sort((a,b)=>b.claims.length-a.claims.length).slice(0,2).map(b=>[P.get(b.element), b.claims.length, L.get(b.winner!)]));
const wr = waiverRecord(tx.transactions, seasons, ids).sort((a,b)=>b.claims-a.claims); console.log("claims", wr.slice(0,2).map(r=>[L.get(r.entryId), r.claims, r.won]));
const moves = { transactions: tx.transactions, trades: t, draft: draft.choices };
const own = new Set<number>(); gws.forEach((gw:any)=>Object.values(gw.squads).forEach((s:any)=>[...s.played,...s.bench].forEach((i:number)=>own.add(i))));
const tr = [...own].map(id=>({id, n: new Set(playerJourney(id, seasons, moves).map(s=>s.entryId)).size})).sort((a,b)=>b.n-a.n).slice(0,3); console.log("travelled", tr.map(x=>[P.get(x.id), x.n]));
